### ISSUE TITLE
Two disk game support

### ISSUE THREAD

**Issue by n1ghttrap** [libretro/quasi88-libretro#1]
Not sure if this feature's broken or I just can't intuit how to use it as there's no clear cut documentation on it.  How do I load two disk games using this core?  Do the files have to be named a certain way in an archive?  Thanks in advance.

**Comment by celerizer** [comment]
Two-disk games are loaded via subsystem interface. After you load the core, you can load both disks via the Load 2-Disk Game option that shows up. When 2 disks are loaded the name of the option changes to Start 2-Disk Game.

I'll close this for now and add a short video to the readme soon.
