### ISSUE TITLE
Correct filetype support

### ISSUE THREAD

**Issue by Sanaki** [libretro/quasi88-libretro#11]
tl;dr: .m3u and .u88 filetype support aren't listed by the core.

According to [the page on libretro docs](https://docs.libretro.com/library/quasi88/), m3u playlists are supported, but the core isn't listed as supporting the .m3u file type and thus attempts to open an m3u file fail, even with the core running. While not currently relevant to me, the docs also list .u88 as supported for user disks, but the core info only lists .d88.

**Comment by celerizer** [comment]
Hi Sanaki, have you run Online Updater > Update Core Info Files in RetroArch recently? The core should have the M3U file type specified where needed and I don't have any issues loading them on any platform.

https://github.com/libretro/quasi88-libretro/blob/master/src/LIBRETRO/libretro.c#L675
https://github.com/libretro/libretro-super/blob/master/dist/info/quasi88_libretro.info#L3

**Comment by Sanaki** [comment]
Strange. I literally just installed the core today from the updater, so that's not the issue. When I go to load an m3u, with or without the core already running, it won't show up in the list. I'm playing on linux in case that's relevant, but to my understanding it shouldn't be. Version shows as RetroArch 1.8.0 with QUASI88 0.6.4.

Listed file support:
![quasi88support](https://user-images.githubusercontent.com/1374333/67761488-476f4600-fa3b-11e9-9df4-971f65d0770d.png)

Attempting to load an m3u with the core loaded already:
![Screenshot from 2019-10-29 04-02-25](https://user-images.githubusercontent.com/1374333/67761655-9f0db180-fa3b-11e9-9a21-a6a93e742d80.png)
