### ISSUE TITLE
Return binding doesn't work

### ISSUE THREAD

**Issue by Sanaki** [libretro/quasi88-libretro#14]
I tested binding return to a couple controller buttons and it doesn't function at all. Space at least works fine. I didn't test other bindings. Tested start and B on Super Jack (adult game, fair warning).

**Comment by ofry** [comment]
Same problem. Tested with Hydlide.

**Comment by bslenul** [comment]
Just encountered the issue and was about to open an issue about it :p 

Got it to work by adding "RETURN" and "RETURNR" for Start button, like this:
```diff
diff --git a/src/LIBRETRO/libretro.c b/src/LIBRETRO/libretro.c
index 2088ede..b8fd925 100644
--- a/src/LIBRETRO/libretro.c
+++ b/src/LIBRETRO/libretro.c
@@ -221,7 +221,9 @@ static void handle_input(void)
    handle_pad(KEY88_X,       RETRO_DEVICE_ID_JOYPAD_A,      0);
    handle_pad(KEY88_Z,       RETRO_DEVICE_ID_JOYPAD_B,      0);
    handle_pad(KEY88_SPACE,   RETRO_DEVICE_ID_JOYPAD_Y,      0);
+   handle_pad(KEY88_RETURN,  RETRO_DEVICE_ID_JOYPAD_START,  0);
    handle_pad(KEY88_RETURNL, RETRO_DEVICE_ID_JOYPAD_START,  0);
+   handle_pad(KEY88_RETURNR, RETRO_DEVICE_ID_JOYPAD_START,  0);
    handle_pad(KEY88_I,       RETRO_DEVICE_ID_JOYPAD_SELECT, 0);
 
    handle_pad(KEY88_R,      RETRO_DEVICE_ID_JOYPAD_UP,     1);
```
Not making a PR because I have absolutely no idea if this is a proper fix or not, but from what I've tested it seems to work fine.
