### ISSUE TITLE
[Support request] BIOS details - n88n.rom

### ISSUE THREAD

**Issue by ofry** [libretro/quasi88-libretro#17]
`n88n.rom` - what is the file? Could you provide me more info? (its size, other hashes, possible filenames in any "romset" (Neo Kobe, for example)

**Comment by hasenbanck** [comment]
It's documented here:
https://docs.libretro.com/library/quasi88/
And here:
https://github.com/RetroPie/RetroPie-Setup/wiki/PC-8800

**Comment by ofry** [comment]
@hasenbanck Thank you.

@celerizer Could you add to documentation this info?

> Sometimes disk.rom is named n88sub.rom and n88n.rom is named n80.rom, so just rename them if you have those.

Source: https://www.reddit.com/r/miniSNESmods/comments/br9i84/quasi88_core_bblackscreen/

**Comment by bslenul** [comment]
Ah, glad I posted that on reddit then :D 

But yeah, I was struggling finding the correct files until I found more infos on the website of the creator of Quasi88: https://www.eonet.ne.jp/~showtime/quasi88/memo/rom.html

![image](https://user-images.githubusercontent.com/33353403/69477734-315e6680-0dea-11ea-9664-6692fca0fb80.png)

**Comment by celerizer** [comment]
n88n.rom is the first entry in the table of filenames the original emu searches for for N-BASIC, that's what I based the docs for quasi88-libretro on.

This problem should be fixed with the newest commit; it'll try both common filenames for each BIOS.
