### ISSUE TITLE
Propagate fail to save/load state to frontend

### ISSUE THREAD

**Issue by ofry** [libretro/quasi88-libretro#23]
If state failed to load, then frontend should "know" that.

There is screenshot with problem:
![Screenshot - 21_03](https://user-images.githubusercontent.com/11790863/77234217-a89bdf80-6bbd-11ea-88bb-fdbdd1bc8856.jpg)

**Comment by celerizer** [comment]
Looks like this is unrelated to the core; the RetroArch widget tracks whether the file was loaded fully from the disk or not, not whether it was valid data
