### ISSUE TITLE
[request] Documentation about core in libretro docs page

### ISSUE THREAD

**Issue by ofry** [libretro/quasi88-libretro#4]
I mean page on this repo: https://github.com/libretro/docs

**Comment by ofry** [comment]
@celerizer @twinaphex @yoshisuga

**Comment by celerizer** [comment]
Fixed with https://github.com/libretro/docs/pull/410

**Comment by ofry** [comment]
@celerizer I don't see link to this page in left sidebar of https://docs.libretro.com/

Please reopen this issue.
