### ISSUE TITLE
[Regression] Core overwrites rom even when option is set to write to srm

### ISSUE THREAD

**Issue by Sanaki** [libretro/quasi88-libretro#44]
As stated, the rom will be overwritten regardless of the option's state. This is clearly unintended and undesirable. Seems it's been this way for quite a while now. Bisect result:
d73f70f7d6656e7ecf80b9c714a9083ba7b3a1ca is the first bad commit

**Comment by celerizer** [comment]
I can't seem to reproduce this one unfortunately. It does seem like a serious issue but I believe you're the only one it's affected.

**Comment by Sanaki** [comment]
Unfortunately I can verify this still happens. I just tested on The Scheme with a non-archived copy of the game, loaded via m3u. Kill the first save and rename it, you'll find the disk 2 file has been written. I can also verify this affects more than me, since I only tested and filed the report after having someone else bring the issue to my attention.

**Comment by celerizer** [comment]
@Sanaki Could you try again after latest commit?

**Comment by Sanaki** [comment]
That resolved it, thanks.
