### ISSUE TITLE
Issues with some games (d88 format)

### ISSUE THREAD

**Issue by Gogerad** [libretro/quasi88-libretro#46]
Hello,

I've notices some games won't launch with libretro quasi88 : 
 - Mugen Senshi Valis : The games freeze after the telenet logo
 - Thexder... launch but black screen

Some others games must have the same issue.

I've tested the quasi88 standalone and everything works fine with it

My roms are in d88 format extension.
I've tested both stand alone and libretro core with same bios and roms.

**Comment by Darknior** [comment]
Same for me, i have try all the core options but impossible to fix them.
Maybe this core is not update to the last standalone version ?

**Comment by celerizer** [comment]
![image](https://user-images.githubusercontent.com/33245078/122600078-e2fc6280-d034-11eb-8736-94df34dcf4b7.png)
![image](https://user-images.githubusercontent.com/33245078/122599934-b6484b00-d034-11eb-951a-84f7de0f1e16.png)

Try with the Sub-CPU option set to 1 or 2.

**Comment by Gogerad** [comment]
Thanks for the find. It works now :)
