### ISSUE TITLE
[Switch] Disk files remain open when the core closes

### ISSUE THREAD

**Issue by cucholix** [libretro/quasi88-libretro#47]
Using latest quasi88 as 5-june 2021, and it’s not possible load a game from playlist when the same game as been previously closed.

Steps:
1 Load game X from playlist 
2 Close game X from Quick Menu
3 Load the same game X from playlist 
4 A message error will appear “File could not  be loaded from playlist”

Loading the game from contents doesn’t have this behavior

**Comment by celerizer** [comment]
Are you sure this is a problem with the core itself, and not RetroArch? Can
you describe what software you're trying to load?

**Comment by cucholix** [comment]
The game is “Choplifter.d88” but any game exhibits this same issue. I’ve tried other cores with the same RA build as quasi88 and don’t have this issue.

**Comment by celerizer** [comment]
Could you take a look at the history playlist with a text editor and
confirm it points to the correct location?

As well, are you using the option that saves changes back to the disk
instead of saving them separately? If so, make sure the disk isn't being
edited to contain garbage after first boot.

I don't have a statically linked platform to test on unfortunately, but
this is an issue I've never seen while playing on either Switch or 3DS.

**Comment by cucholix** [comment]
I generate a clean history playlist:
`/roms/NEC - PC-8800/Gradius (1986)(Konami).d88

/retroarch/cores/quasi88_libretro_libnx.nro
NEC - PC-8000 / PC-8800 series (QUASI88)


default_core_path = ""
default_core_name = ""
label_display_mode = "0"
thumbnail_mode = "0|0"
sort_mode = "2"`

I booted Gradius again after closing the content, it boot just fine the first time but not the second time.
These are the Gradius options:
![quasi88](https://user-images.githubusercontent.com/16081693/120906000-f3b7dc00-c623-11eb-86a7-00b97daac425.jpg)
As workaround I restart Retroarch after using a quasi88 game, or doesn't boot the same game twice.

**Comment by Ploggy** [comment]
I can confirm the Playlist issue, same thing happens to me when I try to load the same game twice from Playlist. (on Switch)

**Comment by celerizer** [comment]
I've talked through this issue with @cucholix on Discord. The file handles for loaded disks aren't explicitly being freed when the core closes (retro_deinit). Should be an easy fix I can handle but I don't have a Switch to test on.

**Comment by cucholix** [comment]
@celerizer I can build for Switch locally if you want to test changes.

**Comment by celerizer** [comment]
@cucholix The latest commit seems to fix the problem on my machine; if you can test on Switch we can close this

**Comment by cucholix** [comment]
I can confirm this commit fixes the playlist issue on Switch
