### ISSUE TITLE
[enhancement] Search firmware in subdirectory of system dir

### ISSUE THREAD

**Issue by ofry** [libretro/quasi88-libretro#8]
Just because some filenames conflict with firmwares of other systems, so user can't use both of them.

**Comment by celerizer** [comment]
It already does this. BIOS go in system/quasi88

**Comment by ofry** [comment]
Then it should be in core info file too.

**Comment by ofry** [comment]
Core info files located in this repository: https://github.com/libretro/libretro-super

**Comment by celerizer** [comment]
I don't really understand the issue, the core info files already specify the quasi88 subfolder and Core Information correctly labels them as present.

**Comment by ofry** [comment]
@celerizer Thank you for fixing this by https://github.com/libretro/libretro-super/commit/ea707c6c71ce0d397e26c1fbf2a89cb058e7aaf7 this commit :)
